apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-5yuv
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-5yuv@sha256:906b36297cc1b65ebeca8c5a4734c504aef58d7917fbadb3a328e7a18ccfd9ad
        name: my-nodejs
        resources: {}
status: {}
